# This file was auto-generated by Fern from our API Definition.

from .openai_compatible_create_transcription_request_timestamp_granularities_item import (
    OpenaiCompatibleCreateTranscriptionRequestTimestampGranularitiesItem,
)
from .openai_compatible_create_transcription_response import OpenaiCompatibleCreateTranscriptionResponse
from .openai_compatible_create_translation_request_model import OpenaiCompatibleCreateTranslationRequestModel
from .openai_compatible_create_translation_response import OpenaiCompatibleCreateTranslationResponse

__all__ = [
    "OpenaiCompatibleCreateTranscriptionRequestTimestampGranularitiesItem",
    "OpenaiCompatibleCreateTranscriptionResponse",
    "OpenaiCompatibleCreateTranslationRequestModel",
    "OpenaiCompatibleCreateTranslationResponse",
]
