# This file was auto-generated by Fern from our API Definition.

import typing

OpenaiCompatibleCreateTranscriptionRequestTimestampGranularitiesItem = typing.Union[
    typing.Literal["word", "segment"], typing.Any
]
