# This file was auto-generated by Fern from our API Definition.

import typing
from ...types.open_ai_create_transcription_response_verbose_json import OpenAiCreateTranscriptionResponseVerboseJson
from ...types.open_ai_create_transcription_response_json import OpenAiCreateTranscriptionResponseJson

OpenaiCompatibleCreateTranscriptionResponse = typing.Union[
    OpenAiCreateTranscriptionResponseVerboseJson, OpenAiCreateTranscriptionResponseJson
]
