# This file was auto-generated by Fern from our API Definition.

import typing

OpenaiCompatibleCreateTranslationRequestModel = typing.Union[
    str, typing.Literal["openai.whisper-1"], typing.Literal["deepgram.whisper-large"]
]
