# This file was auto-generated by Fern from our API Definition.

import typing
from ...types.open_ai_create_translation_response_verbose_json import OpenAiCreateTranslationResponseVerboseJson
from ...types.open_ai_create_translation_response_json import OpenAiCreateTranslationResponseJson

OpenaiCompatibleCreateTranslationResponse = typing.Union[
    OpenAiCreateTranslationResponseVerboseJson, OpenAiCreateTranslationResponseJson
]
