# coding: utf-8

"""
    Speechall API

    The Speechall REST API provides powerful and flexible speech-to-text capabilities. It allows you to transcribe audio files using various underlying STT providers and models, optionally apply custom text replacement rules, and access results in multiple formats. The API includes standard endpoints for transcription and endpoints compatible with the OpenAI API structure. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.open_ai_compatible_speech_to_text_api import OpenAICompatibleSpeechToTextApi  # noqa: E501


class TestOpenAICompatibleSpeechToTextApi(unittest.TestCase):
    """OpenAICompatibleSpeechToTextApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OpenAICompatibleSpeechToTextApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_openai_compatible_create_transcription(self) -> None:
        """Test case for openai_compatible_create_transcription

        Transcribes audio into the input language, using OpenAI-compatible request format.  # noqa: E501
        """
        pass

    def test_openai_compatible_create_translation(self) -> None:
        """Test case for openai_compatible_create_translation

        Translates audio into English, using OpenAI-compatible request format.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
