# coding: utf-8

"""
    Speechall API

    The Speechall REST API provides powerful and flexible speech-to-text capabilities. It allows you to transcribe audio files using various underlying STT providers and models, optionally apply custom text replacement rules, and access results in multiple formats. The API includes standard endpoints for transcription and endpoints compatible with the OpenAI API structure. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.open_ai_transcription_word import OpenAITranscriptionWord  # noqa: E501

class TestOpenAITranscriptionWord(unittest.TestCase):
    """OpenAITranscriptionWord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OpenAITranscriptionWord:
        """Test OpenAITranscriptionWord
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OpenAITranscriptionWord`
        """
        model = OpenAITranscriptionWord()  # noqa: E501
        if include_optional:
            return OpenAITranscriptionWord(
                word = '',
                start = 1.337,
                end = 1.337
            )
        else:
            return OpenAITranscriptionWord(
                word = '',
                start = 1.337,
                end = 1.337,
        )
        """

    def testOpenAITranscriptionWord(self):
        """Test OpenAITranscriptionWord"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
