# coding: utf-8

"""
    Speechall API

    The Speechall REST API provides powerful and flexible speech-to-text capabilities. It allows you to transcribe audio files using various underlying STT providers and models, optionally apply custom text replacement rules, and access results in multiple formats. The API includes standard endpoints for transcription and endpoints compatible with the OpenAI API structure. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class OpenAIAudioResponseFormat(str, Enum):
    """
    The format of the output, in one of these options: `json`, `text`, `srt`, `verbose_json`, or `vtt`. 
    """

    """
    allowed enum values
    """
    JSON = 'json'
    TEXT = 'text'
    SRT = 'srt'
    VERBOSE_JSON = 'verbose_json'
    VTT = 'vtt'

    @classmethod
    def from_json(cls, json_str: str) -> OpenAIAudioResponseFormat:
        """Create an instance of OpenAIAudioResponseFormat from a JSON string"""
        return OpenAIAudioResponseFormat(json.loads(json_str))


