# This file was auto-generated by Fern from our API Definition.

from .types import (
    OpenaiCompatibleCreateTranscriptionRequestTimestampGranularitiesItem,
    OpenaiCompatibleCreateTranscriptionResponse,
    OpenaiCompatibleCreateTranslationRequestModel,
    OpenaiCompatibleCreateTranslationResponse,
)

__all__ = [
    "OpenaiCompatibleCreateTranscriptionRequestTimestampGranularitiesItem",
    "OpenaiCompatibleCreateTranscriptionResponse",
    "OpenaiCompatibleCreateTranslationRequestModel",
    "OpenaiCompatibleCreateTranslationResponse",
]
