# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing
from .open_ai_transcription_segment import OpenAiTranscriptionSegment
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class OpenAiCreateTranslationResponseVerboseJson(UniversalBaseModel):
    language: str = pydantic.Field()
    """
    The language of the output translation (always `english`).
    """

    duration: str = pydantic.Field()
    """
    The duration of the input audio.
    """

    text: str = pydantic.Field()
    """
    The translated text.
    """

    segments: typing.Optional[typing.List[OpenAiTranscriptionSegment]] = pydantic.Field(default=None)
    """
    Segments of the translated text and their corresponding details.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
