# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing
from .open_ai_transcription_word import OpenAiTranscriptionWord
from .open_ai_transcription_segment import OpenAiTranscriptionSegment
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class OpenAiCreateTranscriptionResponseVerboseJson(UniversalBaseModel):
    """
    Represents a verbose json transcription response returned by model, based on the provided input.
    """

    language: str = pydantic.Field()
    """
    The language of the input audio.
    """

    duration: float = pydantic.Field()
    """
    The duration of the input audio.
    """

    text: str = pydantic.Field()
    """
    The transcribed text.
    """

    words: typing.Optional[typing.List[OpenAiTranscriptionWord]] = pydantic.Field(default=None)
    """
    Extracted words and their corresponding timestamps.
    """

    segments: typing.Optional[typing.List[OpenAiTranscriptionSegment]] = pydantic.Field(default=None)
    """
    Segments of the transcribed text and their corresponding details.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
