# coding: utf-8

# flake8: noqa

"""
    Speechall API

    The Speechall REST API provides powerful and flexible speech-to-text capabilities. It allows you to transcribe audio files using various underlying STT providers and models, optionally apply custom text replacement rules, and access results in multiple formats. The API includes standard endpoints for transcription and endpoints compatible with the OpenAI API structure. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.open_ai_compatible_speech_to_text_api import OpenAICompatibleSpeechToTextApi
from openapi_client.api.replacement_rules_api import ReplacementRulesApi
from openapi_client.api.speech_to_text_api import SpeechToTextApi

# import ApiClient
from openapi_client.api_response import ApiResponse
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
from openapi_client.exceptions import OpenApiException
from openapi_client.exceptions import ApiTypeError
from openapi_client.exceptions import ApiValueError
from openapi_client.exceptions import ApiKeyError
from openapi_client.exceptions import ApiAttributeError
from openapi_client.exceptions import ApiException

# import models into sdk package
from openapi_client.models.base_transcription_configuration import BaseTranscriptionConfiguration
from openapi_client.models.create_replacement_ruleset201_response import CreateReplacementRuleset201Response
from openapi_client.models.create_replacement_ruleset_request import CreateReplacementRulesetRequest
from openapi_client.models.error_response import ErrorResponse
from openapi_client.models.exact_rule import ExactRule
from openapi_client.models.open_ai_audio_response_format import OpenAIAudioResponseFormat
from openapi_client.models.open_ai_create_transcription_response_json import OpenAICreateTranscriptionResponseJson
from openapi_client.models.open_ai_create_transcription_response_verbose_json import OpenAICreateTranscriptionResponseVerboseJson
from openapi_client.models.open_ai_create_translation_request_model import OpenAICreateTranslationRequestModel
from openapi_client.models.open_ai_create_translation_response_json import OpenAICreateTranslationResponseJson
from openapi_client.models.open_ai_create_translation_response_verbose_json import OpenAICreateTranslationResponseVerboseJson
from openapi_client.models.open_ai_transcription_segment import OpenAITranscriptionSegment
from openapi_client.models.open_ai_transcription_word import OpenAITranscriptionWord
from openapi_client.models.openai_compatible_create_transcription200_response import OpenaiCompatibleCreateTranscription200Response
from openapi_client.models.openai_compatible_create_translation200_response import OpenaiCompatibleCreateTranslation200Response
from openapi_client.models.regex_group_rule import RegexGroupRule
from openapi_client.models.regex_rule import RegexRule
from openapi_client.models.remote_transcription_configuration import RemoteTranscriptionConfiguration
from openapi_client.models.replacement_rule import ReplacementRule
from openapi_client.models.speech_to_text_model import SpeechToTextModel
from openapi_client.models.transcript_language_code import TranscriptLanguageCode
from openapi_client.models.transcript_output_format import TranscriptOutputFormat
from openapi_client.models.transcription_detailed import TranscriptionDetailed
from openapi_client.models.transcription_model_identifier import TranscriptionModelIdentifier
from openapi_client.models.transcription_only_text import TranscriptionOnlyText
from openapi_client.models.transcription_provider import TranscriptionProvider
from openapi_client.models.transcription_response import TranscriptionResponse
from openapi_client.models.transcription_segment import TranscriptionSegment
from openapi_client.models.transcription_word import TranscriptionWord
