# This file was auto-generated by Fern from our API Definition.

import typing

TranscriptionProvider = typing.Union[
    typing.Literal[
        "assemblyai",
        "azure",
        "cloudflare",
        "deepgram",
        "elevenlabs",
        "gemini",
        "gladia",
        "groq",
        "ibm",
        "mistral",
        "openai",
        "revai",
        "smallestai",
        "soniox",
        "speechmatics",
        "togetherai",
        "xai",
    ],
    typing.Any,
]
