# This file was auto-generated by Fern from our API Definition.

import typing
from ..core.client_wrapper import SyncClientWrapper
from ..types.replacement_rule import ReplacementRule
from ..core.request_options import RequestOptions
from .types.create_replacement_ruleset_response import CreateReplacementRulesetResponse
from ..core.serialization import convert_and_respect_annotation_metadata
from ..core.pydantic_utilities import parse_obj_as
from ..errors.bad_request_error import BadRequestError
from ..types.error_response import ErrorResponse
from ..errors.unauthorized_error import UnauthorizedError
from ..errors.payment_required_error import PaymentRequiredError
from ..errors.too_many_requests_error import TooManyRequestsError
from ..errors.internal_server_error import InternalServerError
from ..errors.service_unavailable_error import ServiceUnavailableError
from ..errors.gateway_timeout_error import GatewayTimeoutError
from json.decoder import JSONDecodeError
from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ReplacementRulesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def create_replacement_ruleset(
        self,
        *,
        name: str,
        rules: typing.Sequence[ReplacementRule],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateReplacementRulesetResponse:
        """
        Defines a named set of replacement rules (exact match, regex) that can be applied during transcription requests using its `ruleset_id`.
        Rules within a set are applied sequentially to the transcription text.

        Parameters
        ----------
        name : str
            A user-defined name for this ruleset for easier identification.

        rules : typing.Sequence[ReplacementRule]
            An ordered array of replacement rules. Rules are applied in the order they appear in this list. See the `ReplacementRule` schema for different rule types (exact, regex, regex_group).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateReplacementRulesetResponse
            Ruleset created successfully. The response body contains the unique ID assigned to the new ruleset.

        Examples
        --------
        from speechall import ReplacementRule_Exact, ReplacementRule_Regex, Speechall

        client = Speechall(
            token="YOUR_TOKEN",
        )
        client.replacement_rules.create_replacement_ruleset(
            name="Acme Corp Corrections",
            rules=[
                ReplacementRule_Exact(
                    search="customer X",
                    replacement="[REDACTED CUSTOMER NAME]",
                ),
                ReplacementRule_Regex(
                    pattern="\\b\\d{4}\\b",
                    replacement="[REDACTED YEAR]",
                ),
            ],
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "replacement-rulesets",
            method="POST",
            json={
                "name": name,
                "rules": convert_and_respect_annotation_metadata(
                    object_=rules, annotation=typing.Sequence[ReplacementRule], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    CreateReplacementRulesetResponse,
                    parse_obj_as(
                        type_=CreateReplacementRulesetResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 402:
                raise PaymentRequiredError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 504:
                raise GatewayTimeoutError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncReplacementRulesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def create_replacement_ruleset(
        self,
        *,
        name: str,
        rules: typing.Sequence[ReplacementRule],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateReplacementRulesetResponse:
        """
        Defines a named set of replacement rules (exact match, regex) that can be applied during transcription requests using its `ruleset_id`.
        Rules within a set are applied sequentially to the transcription text.

        Parameters
        ----------
        name : str
            A user-defined name for this ruleset for easier identification.

        rules : typing.Sequence[ReplacementRule]
            An ordered array of replacement rules. Rules are applied in the order they appear in this list. See the `ReplacementRule` schema for different rule types (exact, regex, regex_group).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateReplacementRulesetResponse
            Ruleset created successfully. The response body contains the unique ID assigned to the new ruleset.

        Examples
        --------
        import asyncio

        from speechall import (
            AsyncSpeechall,
            ReplacementRule_Exact,
            ReplacementRule_Regex,
        )

        client = AsyncSpeechall(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.replacement_rules.create_replacement_ruleset(
                name="Acme Corp Corrections",
                rules=[
                    ReplacementRule_Exact(
                        search="customer X",
                        replacement="[REDACTED CUSTOMER NAME]",
                    ),
                    ReplacementRule_Regex(
                        pattern="\\b\\d{4}\\b",
                        replacement="[REDACTED YEAR]",
                    ),
                ],
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "replacement-rulesets",
            method="POST",
            json={
                "name": name,
                "rules": convert_and_respect_annotation_metadata(
                    object_=rules, annotation=typing.Sequence[ReplacementRule], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    CreateReplacementRulesetResponse,
                    parse_obj_as(
                        type_=CreateReplacementRulesetResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 402:
                raise PaymentRequiredError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 504:
                raise GatewayTimeoutError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
